copy_sheet_location = "copysheet.xlsx"
web_app_location = "../web_app"
static_files_location = "../static"
template_folders_location = "../templates"
external_url = "http://interactives.dailytexanonline.com/student-elections-explorer/"